{"name": "test_login_fail[case2]", "status": "passed", "attachments": [{"name": "log", "source": "6689e148-c76f-47f3-a337-43684f86e280-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误，登录第二次', 'phone': '17610772806', 'pwd': 'python22', 'expected': '密码错误, 你还可以尝试3次'}"}], "start": 1604473485524, "stop": 1604473486209, "uuid": "31a15059-6c88-4f22-9ca0-53944f5ef050", "historyId": "90cd6acc08bdb2a20d7bb2a873ca5f00", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "14501-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}