{"name": "test_login_fail[case2]", "status": "passed", "attachments": [{"name": "log", "source": "f6cd1a3a-5e17-4159-bbaa-0f7502aab2f9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误，登录第二次', 'phone': '17610772806', 'pwd': 'python22', 'expected': '密码错误, 你还可以尝试3次'}"}], "start": 1604461896902, "stop": 1604461897582, "uuid": "c74e2c8b-3cf9-4cfb-b978-c79c66f4057a", "historyId": "90cd6acc08bdb2a20d7bb2a873ca5f00", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "55631-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}