{"name": "test_login_fail[case3]", "status": "passed", "attachments": [{"name": "log", "source": "9e4a0763-e72f-4fa3-81c3-fb6c58d9e9cf-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误，登录第三次', 'phone': '17610772806', 'pwd': 'python22', 'expected': '密码错误, 你还可以尝试2次'}"}], "start": 1604474245050, "stop": 1604474245790, "uuid": "ecd378c9-1ee3-4def-9bd3-14b2c0663f0a", "historyId": "c7bde7902c558644f50cbda526351fdf", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "18542-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}