{"uuid": "44fe4e8c-3923-402a-9804-4ff851416e36", "children": ["87261e91-26cf-467f-8292-1beb025bd86f", "7df8e04e-fa0a-4a66-91c9-da6646386016", "80429ab3-d1eb-49e4-9254-3c52f1716173", "d1f6ad89-86d6-42cb-8df8-5467a91fc58a", "337bba61-6175-44c1-9e81-ac87c93f1cfe", "32fe582c-8d6e-4877-b2d1-dc7d6975d278", "ad601919-16a3-436b-a704-00f399f88aa3", "3712eb59-b95f-43b2-a499-91ff2fd9c802", "5f6e329b-3ae4-4063-9662-9c99158fb355", "10bb39d8-b349-4c78-99ab-113125203948", "9fbb029f-74df-47db-9d68-321dd82a301c", "728e5247-c8c2-40ca-a232-71c2bcce8167", "6259aaed-1264-4349-9467-494db6c2bde3", "4357884d-1d21-48e5-bed5-a856c35732dc", "43b1c260-df21-43e3-bb60-c64dc3ca761d", "42682a5e-7bc5-4ffb-b80c-3c0c35704e91", "2ad0f25d-e5b8-4475-955d-4738cdd70186", "54211159-c356-4a5d-9525-70aa7a3c4b32", "d29e248d-0d18-4459-813d-6aeed2838230", "04f7e518-a8b9-4e94-a922-98a4c3b98004", "982d1580-b476-49d6-b822-4c5cbe43e291", "a0e74ebc-6155-4111-9b95-42725cdb3362"], "befores": [{"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473623962, "stop": 1604473641868}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473644128, "stop": 1604473663231}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473665293, "stop": 1604473683342}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473685401, "stop": 1604473704114}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473706225, "stop": 1604473725333}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473727388, "stop": 1604473746247}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473748303, "stop": 1604473767332}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473769792, "stop": 1604473788150}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473790210, "stop": 1604473808118}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473810179, "stop": 1604473829439}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473831543, "stop": 1604473849515}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473851576, "stop": 1604473870045}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473872321, "stop": 1604473890450}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473892561, "stop": 1604473911511}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473913566, "stop": 1604473931735}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 152, in click_element\n    file_name = \"{}_{}.png\".format(img_info)\n"}, "start": 1604473933794, "stop": 1604473951908}, {"name": "personal_setup", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/testcase/conftest.py\", line 95, in personal_setup\n    index_page.take_course()\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/page/Index_page.py\", line 61, in take_course\n    self.click_element(self.take_course_locator,\"首页_点击进入班级\")\n  File \"/Users/zhangcaiyan/Desktop/ketangpai/common/base_page.py\", line 146, in click_element\n    self.driver.find_element(*locator).click()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/request.py\", line 70, in request\n    **urlopen_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/request.py\", line 148, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/poolmanager.py\", line 321, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n    chunked=chunked)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 383, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py\", line 1336, in getresponse\n    response.begin()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py\", line 306, in begin\n    version, status, reason = self._read_status()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py\", line 267, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py\", line 589, in readinto\n    return self._sock.recv_into(b)\n"}, "start": 1604473954039, "stop": 1604473959498}], "start": 1604473954039, "stop": 1604473960227}