{"name": "test_login_fail[case1]", "status": "passed", "attachments": [{"name": "log", "source": "7018bca7-873d-4def-9292-006eca27b22f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误，登录第一次', 'phone': '17610772806', 'pwd': 'python22', 'expected': '密码错误, 你还可以尝试4次'}"}], "start": 1604474243691, "stop": 1604474244392, "uuid": "71b854ae-7aa2-4225-a1e2-da61b4685cc0", "historyId": "3790ea8f588a67734f18e931be1970f9", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "18542-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}