{"name": "test_login_fail[case1]", "status": "passed", "attachments": [{"name": "log", "source": "e1ca1508-6d84-416c-a963-f2bfe292a40d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误，登录第一次', 'phone': '17610772806', 'pwd': 'python22', 'expected': '密码错误, 你还可以尝试4次'}"}], "start": 1604461896186, "stop": 1604461896899, "uuid": "9bbe3d0f-20de-46b7-a467-4ce6c0a49f11", "historyId": "3790ea8f588a67734f18e931be1970f9", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "55631-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}