{"name": "test_login_fail[case2]", "status": "passed", "attachments": [{"name": "log", "source": "70732531-8e59-4961-b492-36cce55b98be-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误，登录第二次', 'phone': '17610772806', 'pwd': 'python22', 'expected': '密码错误, 你还可以尝试3次'}"}], "start": 1604474244396, "stop": 1604474245046, "uuid": "6237cd8e-8c1a-4072-9889-e5d63a93ecbf", "historyId": "90cd6acc08bdb2a20d7bb2a873ca5f00", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "18542-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}