{"name": "test_login_fail[case1]", "status": "passed", "attachments": [{"name": "log", "source": "14347144-97fc-4933-967e-0892d43b787a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误，登录第一次', 'phone': '17610772806', 'pwd': 'python22', 'expected': '密码错误, 你还可以尝试4次'}"}], "start": 1604473484866, "stop": 1604473485520, "uuid": "85550aa7-443e-401d-9437-fbe4d23b825d", "historyId": "3790ea8f588a67734f18e931be1970f9", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "14501-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}