{"name": "test_login_fail[case3]", "status": "passed", "attachments": [{"name": "log", "source": "1bb46e82-4dab-463c-8c2a-02689791b88f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '密码错误，登录第三次', 'phone': '17610772806', 'pwd': 'python22', 'expected': '密码错误, 你还可以尝试2次'}"}], "start": 1604473486213, "stop": 1604473486890, "uuid": "30b3ecb3-93e1-463c-8da4-287750b25771", "historyId": "c7bde7902c558644f50cbda526351fdf", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "14501-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}